# raise an exception with message

def raise_exception_msg(message=""):
    raise NameError (message)
